# Great reference for modifying Application to your needs: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: jenkins
    server: 'https://kubernetes.default.svc'
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true  
  sources:
  - repoURL: https://charts.jenkins.io/
    targetRevision: 5.7.12 # Change version here
    chart: jenkins
    # helm:
    #   valueFiles:
    #   - $values/kubernetes/active/jenkins/values.yaml # Change where your values file is in remote repository. $values is at root.
  - repoURL: 'https://github.com/some-user/private-values-repo' # Change this to point to where your values file is restored.
    targetRevision: main
    ref: values 
  project: default